<FileChooserDialog>:
  BoxLayout:
    size: root.size
    pos: root.pos
    orientation: 'vertical'
    FileChooserIconView:
      id: file_chooser
      filters: root.filter
      path: root.path

    BoxLayout:
      size_hint_y: None
      height: 30
      Button:
        text: 'Cancel'
        on_release: root.cancel()
      Button:
        text: 'Load'
        font_size: 10
        on_release: root.load(file_chooser.path, file_chooser.selection)
